PASSO 1
NÃO PRECISA DE QUERY PARA RODAR NO BANCO DE DADOS, O SITE INSTALA SOZINHO, BASTA CONFIGURAR O ARQUIVO "CONFIGURAÇÃO.PHP" NA PASTA PAGES

PASSO 2
APóS CONFIGURADO ENTRAR NO SITE

PASSO 3
CASO TENHA ALGUM ERRO, TROQUE A VERSÃO DO PHP PARA PHP 5.2

PASSO FINAL
PRONTO, SITE PRONTO PARA USO, QUALQUER DÚVIDA CONTATE-NOS! www.mochost.com.br e www.nrscripts.blogspot.com.br

Para adquirir mais scripts php acesse: www.coracaodejesusmg.com/php